# Autonomy levels as string constants
OBSERVE = 'OBSERVE'
ASSISTED = 'ASSISTED'  
AUTONOMOUS = 'AUTONOMOUS'
FULL_AUTONOMOUS = 'FULL_AUTONOMOUS'

__all__ = ['OBSERVE', 'ASSISTED', 'AUTONOMOUS', 'FULL_AUTONOMOUS']

